Traceback (most recent call last):
  File "/usr/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/MinGW/bin/cmake3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/./ns3", line 1615, in <module>
    main()
  File "/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/./ns3", line 1586, in main
    build_step(args,
  File "/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/./ns3", line 1096, in build_step
    cmake_build(current_cmake_cache_folder,
  File "/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/./ns3", line 866, in cmake_build
    cmake, version = cmake_check_version()
  File "/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/./ns3", line 851, in cmake_check_version
    cmake3 = shutil.which("cmake3")
  File "/usr/lib/python3.10/shutil.py", line 1507, in which
    if _access_check(name, mode):
  File "/usr/lib/python3.10/shutil.py", line 1427, in _access_check
    return (os.path.exists(fn) and os.access(fn, mode)
  File "/usr/lib/python3.10/genericpath.py", line 19, in exists
    os.stat(path)
KeyboardInterrupt
