Traceback (most recent call last):
  File "/usr/lib/python3.10/posixpath.py", line 177, in lexists
    os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/build/src/virtual-net-device/CMakeCache.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/./ns3", line 1615, in <module>
    main()
  File "/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/./ns3", line 1508, in main
    current_cmake_cache_folder, current_cmake_generator = search_cmake_cache(build_profile)
  File "/mnt/c/Users/HP/Desktop/3-2-Lab/cse322-Networks/NS3/resources/ns-allinone-3.39/ns-3.39/./ns3", line 510, in search_cmake_cache
    cmake_cache_files = glob.glob("%s/**/CMakeCache.txt" % ns3_path, recursive=True)
  File "/usr/lib/python3.10/glob.py", line 24, in glob
    return list(iglob(pathname, root_dir=root_dir, dir_fd=dir_fd, recursive=recursive))
  File "/usr/lib/python3.10/glob.py", line 86, in _iglob
    for name in glob_in_dir(_join(root_dir, dirname), basename, dir_fd, dironly):
  File "/usr/lib/python3.10/glob.py", line 101, in _glob0
    if _lexists(_join(dirname, basename), dir_fd):
  File "/usr/lib/python3.10/glob.py", line 180, in _lexists
    return os.path.lexists(pathname)
  File "/usr/lib/python3.10/posixpath.py", line 177, in lexists
    os.lstat(path)
KeyboardInterrupt
